### ISSUE TITLE
Add background images to home & schedule page

### ISSUE THREAD

**Issue by llennemann** [CSSA-UCSD/conference2023#2]
# Home
Divided into 3 different images for different sections.

## Landing Image
![image](https://user-images.githubusercontent.com/56721078/233214402-5110166e-652b-46db-82df-1426cc8ef698.png)
Opacity: 75%
Blend: Pass through
Used in the two sections below.

### Top: Conference Theme
- [x] background: linear-gradient(270deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0) 29.99%),
- [x] linear-gradient(90deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0) 29.46%),
- [x] linear-gradient(0deg, rgba(69, 17, 208, 0.2), rgba(69, 17, 208, 0.2));

### Bottom: 01 About 
- [x] background: linear-gradient(180deg, #000000 0%, rgba(0, 0, 0, 0) 49.55%),
- [x] linear-gradient(180deg, #000000 0%, rgba(0, 0, 0, 0) 92.65%),
- [x] linear-gradient(90deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0) 32.44%),
- [x] linear-gradient(270deg, rgba(0, 0, 0, 0.6) 0.03%, rgba(0, 0, 0, 0) 26.85%),
- [x] linear-gradient(0deg, rgba(69, 17, 208, 0.2), rgba(69, 17, 208, 0.2));
- [x] horizontal flip / 180 degree rotation

## 02 Speakers Image
[Orange background](url)
### Top
- [x] background: linear-gradient(360deg, #000000 4.16%, rgba(0, 0, 0, 0) 16.02%);

### Bottom 
- [ ] background: linear-gradient(0deg, #000000 0%, rgba(0, 0, 0, 0) 27.98%);
- [ ] horizontal flip / 180 degree rotation

## 03 Schedule Image
[Borealis background](url)
### Top
- [ ] background: linear-gradient(180deg, #000000 7.8%, rgba(0, 0, 0, 0) 53.25%),
- [ ] linear-gradient(0deg, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0.15));

### Bottom
- [ ] background: linear-gradient(180deg, #000000 1.8%, rgba(0, 0, 0, 0) 77.8%),
- [ ] linear-gradient(0deg, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0.15));
- [ ] horizontal flip / 180 degree rotation

# Schedule 
[link image](url)
Image 2: 70% opacity

**Comment by vchou105** [comment]
Note: the styles are direct copied from figma but i'm not sure if they're exactly correct.
